config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: %i[index show]
  resources :follows, only: %i[create destroy]

  root to: 'users#index'
end

app/models/follow.rb
# frozen_string_literal: true

# following: フォローされる方, follower: フォローする方

class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'

  validates :follower_id, presence: true
  validates :following_id, presence: true
  validate :user_cannot_follow_self
  validate :both_ids_combination_cannot_duplicate

  def user_cannot_follow_self
    errors.add(:following_id, '自分をフォローすることはできません') if follower_id == following_id
  end

  def both_ids_combination_cannot_duplicate
    follow = Follow.find_by(follower_id: follower_id, following_id: following_id)
    errors.add(:following_id, '既にフォローしているユーザーです') if follow
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :followers, class_name: 'Follow', foreign_key: :following_id, dependent: :destroy
  has_many :followings, class_name: 'Follow', foreign_key: :follower_id, dependent: :destroy
  # has_many :followers, through: :follows, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    user = find_or_initialize_by(provider: auth.provider, uid: auth.uid)
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.name = auth.info.name
    user.remote_avatar_url = auth.info.image # Facebook認証の場合remote_avatar_url
    # If you are using confirmable and the provider(s) you use validate emails,
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!

    user.save
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      data = session['devise.facebook_data']
      if data && data['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def follow(following_id)
    followings.create(following_id: following_id)
  end

  def unfollow(following_id)
    followings.find_by(following_id: following_id)&.destroy
  end

  def following_ids_in(ids)
    followings.where(following_id: ids).pluck(:following_id)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/follows_controller.rb
# frozen_string_literal: true

class FollowsController < ApplicationController
  def create
    follow = current_user.follow(following_id)
    if Follow.exists?(follow.id)
      @following_id = following_id
      render format: :js
    else
      flash[:danger] = 'フォローに失敗しました'
      redirect_to root_path

    end
  end

  def destroy
    unfollow = current_user.unfollow(following_id)
    if unfollow
      @following_id = following_id
      render format: :js
    else
      flash[:danger] = 'フォロー解除に失敗しました'
      redirect_to root_path
    end
  end

  private

  def following_id
    params.require(:follow)[:following_id]
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id).page(params[:page])
    @ids_current_user_followings = current_user.following_ids_in @users.ids
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/follows/create.js.erb
var form_wrapper = document.querySelector('#follow-form-<%= @following_id %>')
  .parentElement;
form_wrapper.innerHTML = `<%= render "components/unfollow_btn", following_id: @following_id %>`;

app/views/follows/destroy.js.erb
var form_wrapper = document.querySelector('#follow-form-<%= @following_id %>')
  .parentElement;
form_wrapper.innerHTML = `<%= render "components/follow_btn", following_id: @following_id %>`;

app/views/layouts/_header.html.erb
<% name = current_user.name %>
<nav class="navbar navbar-expand sticky-top navbar-light bg-light">
  <ul class="navbar-nav">
    <li class="nav-item mr-1 mr-lg-3" data-toggle="tooltip" data-placement="top" title="Tooltip on top">
      <%= link_to root_path, class: "nav-link #{"active" if yield(:activate_nav_home_icon).present?}" do %>
        <i class="fas fa-home">
          <h6 class="mb-0 d-none d-lg-inline-block">Home</h6>
        </i>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to '#', class:"nav-link #{"active" if yield(:activate_nav_search_icon).present?}" do %>
        <i class="fas fa-search">
          <h6 class="mb-0 d-none d-lg-inline-block">Search</h6>
        </i>
      <% end %>
    </li>
  </ul>
  <div class="dropdown ml-auto">
    <a id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= image_tag current_user.avatar.icon.url, class: "img-circle border border-secondary rounded-circle" %>
      <span class="d-none d-lg-inline"><%= name %></span>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dLabel">
      <%= link_to "My page", user_path(current_user), class: "dropdown-item" %>
      <%= link_to "Setting", '#', class: "dropdown-item" %>
      <div class="dropdown-divider"></div>
      <%= link_to "Sign out!", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Src</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name= "viewport" content= "width=device-width, initial-scale=1" >
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if current_user %>
      <%= render  "layouts/header" %>
    <% end %>
    <%= render "components/flash" %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% provide(:activate_nav_home_icon, true) %>
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
      <% @users.each do |user| %>
        <% id = user.id %>
        <div class="row">
          <div class="col-12 border-top p-3" href="<%= user_path id %>">
            <%= link_to user_path(user) do %>
              <%= image_tag user.avatar.icon.url, class: "img-circle rounded-circle" %>
              <span class="text-dark"><%= user.name %></span>
            <% end %>
            <div class="float-right">
              <% if @ids_current_user_followings.exclude?(id) %>
                <%= render 'components/follow_btn', following_id: id %>
              <% else %>
                <%= render 'components/unfollow_btn', following_id: id %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <%= image_tag @user.avatar.icon.url, class: "img-circle rounded-circle" %>
  <%= @user.name %>
  <% unless @user == current_user %>
    <div class="float-right">
      <% if current_user.followings.where(following_id: @user.id).empty? %>
        <%= render 'components/follow_btn', following_id: @user.id %>
      <% else %>
        <%= render 'components/unfollow_btn', following_id: @user.id %>
      <% end %>
    </div>
  <% end %>
</div>